services:
  - type: web
    name: prop-shoppe-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && gunicorn prop_shoppe.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: prop_shoppe.settings



