# Generated by Django 5.2.5 on 2025-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='alt_text',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='flashsale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='flashsales/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='alt_text',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/%Y/%m/%d/'),
        ),
    ]
