# Generated by Django 5.2.5 on 2025-08-19 13:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_flashsale_alt_text_flashsale_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='categories/placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='flashsale',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='flashsales/placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='products/placeholder', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='promotions/placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
